fragment Quote on ParagraphQuote {
  partOfNavigator: fieldPartOfNavigatorSidebar
  title: fieldTitle
  quote: fieldPqQuote {
    processed
  }
  quoteTitle: fieldPqQuoteTitle
  quoteCredit: fieldPqQuoteCredit
  color: fieldPqColorsOptions
}