fragment BioLinks on ParagraphBioLinksCard{
  title: fieldTitle
	headline: fieldHeadline
  cards: fieldPblcCards{
    card: entity{
      cardType: __typename
      ...BioCard
      ...LinkCard
    }
	}
}
fragment BioCard on ParagraphBioCard{
  queryType{
    entities{
      entityLabel
    }
  }
  cardTitle: fieldTitle
  name: fieldPbcName
  image: fieldBioImage{
    entity{
    ... on MediaImage {
      fieldMediaImage{
        derivative(style: CARDOVERLAY){
          url
        }
      }
    }
    }
  }
  contentLink: fieldLink{
    url{
      path
    }
  }
  socialMedia: fieldPbcSocialMedias{
    url{
      path
    }
  }
}
fragment LinkCard on ParagraphLinkCard{
  queryType{
    entities{
      entityLabel
    }
  }
  cardTitle: fieldTitle
  links: fieldPlcLinks{
    entity{
      ... on ParagraphLinks{
        fieldLink{
          linkText: title
          url{
            path
          }
        }
        newWindowToggle: fieldOpenInNewWindow
      }
    }
  }
  image: fieldPlcImage{
    entity{
      ... on MediaImage {
        fieldMediaImage{
          derivative(style: CARDLINK){
            url
          }
        }
      }
    }
  }
}