fragment EmergencyPage on NodeEmergency {
	title
  mtaToggle: fieldEToggleMtaWidget
	contentType: entityBundle
	description: fieldEDescription {
		processed
	}
	lastUpdate: fieldELastUpdated {
		date
	}
	twitter: fieldETwitterHandle
	phone: fieldEContactPhone
	updateLink: fieldEUpdateLink {
		title
		url {
			path
		}
	}
	latestUpdatesTitle: fieldEUpdatesTitle
	moreUpdates: fieldEMoreUpdates {
		linkText: title
		url {
			path
		}
	}
	latestUpdatesSection: fieldEUpdates	 {
		content: entity {
			type: __typename
			...LatestUpdates
		}
	}
	sections: fieldSections {
		section: entity {
			type: __typename
			...WYSIWYG
			...PhotoGallery
			...Resources
      ...VideoEmbed
      ...Documents
		}
	}
  alerts: fieldEAlerts {
		section: entity {
			type: __typename
			...Alerts
		}
	}
}
