fragment CardsQueue on ParagraphCardsQueue {
  title: fieldTitle
  cardType: fieldPcqCardType
  subheadline: fieldHeadline
  learnMore: fieldPcqCardLearnMore{
    linkText: title
    url {
      routed
      path
    }
  }
  ariaLabel: fieldPcqAriaLabel
  cardQueue: fieldPcqQueue {
    id: targetId
    card: entity {
      label: entityLabel
      type: entityType
      referenceType: __typename
      ...FieldCardsQueue
      ...FieldServiceCardsQueue
      ...FieldNewsCardsQueue
      ...FieldProgramCardsQueue
      ...FieldScheduledEventCardsQueue
      ...FieldArticleCardsQueue
    }
  }
}

fragment FieldCardsQueue on MediaCard {
  image: fieldMcImage {
    entity {
      ... on MediaImage {
        desktopImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
        tabletImg: fieldMediaImage {
          derivative(style: CARDHORIZONTAL) {
            url
          }
        }
        mobileImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
        statsImg: fieldMediaImage{
          derivative(style:SQUAREEXTRALARGE){
            url
          }
        }
      }
    }
  }
  keywords: fieldMcKeywords {
    entity {
      keyword: entityLabel
      url: entityUrl {
        routed
        path
      }
    }
  }
  description: fieldMcDescription {
    processed
    summaryProcessed
  }
  learnMore: fieldMcLearnMore {
    url {
      routed
      path
    }
    linkText: title
  }
  iosLink: fieldMcIosLink{
    url{
      path
    }
    linkText: title
  }
  androidLink: fieldMcAndroidLink{
    url{
      path
    }
    linkText: title
  }
  chapterLinks: fieldMcChapterLinks {
    url {
      routed
      path
    }
    linkText: title
  }
  fieldStats: fieldMcStats
  fieldStatsLabel: fieldMcStatsLabel
}

fragment FieldServiceCardsQueue on NodeService{
	image: fieldSFeaturedImage{
    entity {
      ... on MediaImage {
        desktopImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
        tabletImg: fieldMediaImage {
          derivative(style: CARDHORIZONTAL) {
            url
          }
        }
        mobileImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
      }
    }
  }
  howToApply: fieldSHowToApply{
    title
    url{
      path
    }
  }
  contentLink: entityUrl{
    routed
    path
  }
  keywords: fieldSKeywords{
    entity{
      keyword: entityLabel
      url: entityUrl {
        routed
        path
      }
    }
  }
  description: fieldSDescription{
    processed
    summaryProcessed
  }
	whiteList: fieldRedirectUrl
  fieldSSubHeadline
  fieldSCategories{
    entity{
      entityLabel
    }
  }

  navigator: fieldSNavigatorToggle

  paragraphs: fieldSections{
    paragraph: entity{
      ... on ParagraphWysiwyg{
      title: fieldTitle
      id
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
      ... on  ParagraphDocuments{
      title: fieldTitle
      id
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
      ... on ParagraphVideoEmbed{
      title: fieldTitle
      id
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
      ... on ParagraphPhotoGallery{
      title: fieldTitle
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
      ... on ParagraphContact{
      title: fieldTitle
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
      ... on ParagraphQuote{
      title: fieldTitle
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
      ... on ParagraphTranslatedDocuments{
      title: fieldTitle
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
      ... on ParagraphWhatsRelated{
      title: fieldTitle
      navAdd: fieldPartOfNavigatorSidebar
      cardAdd: fieldChapterLinkOnCard
      }
    }
  }
  footerText: fieldCardFooterLabel
}

fragment FieldNewsCardsQueue on NodeNews{
  image: fieldNFeaturedImage{
    entity {
      ... on MediaImage {
        desktopImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
        tabletImg: fieldMediaImage {
          derivative(style: CARDHORIZONTAL) {
            url
          }
        }
        mobileImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
      }
    }
  }

  keywords: fieldNKeywords{
    entity{
    keyword: entityLabel
      url: entityUrl{
        path
      }
    }
  }
  cardNLabel:  fieldNTeaserHeadline
  description: fieldNDescription {
    processed
    summaryProcessed
  }
  date: entityCreated
  contentLink: entityUrl{
    routed
    path
  }
}
fragment FieldArticleCardsQueue on NodeArticlePage{
  image: fieldApFeaturedImage{
    entity {
      ... on MediaImage {
        desktopImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
        tabletImg: fieldMediaImage {
          derivative(style: CARDHORIZONTAL) {
            url
          }
        }
        mobileImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
      }
    }
  }
  keywords: fieldApKeywords{
    entity{
    keyword: entityLabel
      url: entityUrl{
        path
      }
    }
  }
  description: fieldApDescription {
    processed
  }
  contentLink: entityUrl {
    path
  }
  footerText: fieldCardFooterLabel
}
fragment FieldProgramCardsQueue on NodeProgram{
	image: fieldPFeaturedImage{
    entity {
      ... on MediaImage {
        desktopImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
        tabletImg: fieldMediaImage {
          derivative(style: CARDHORIZONTAL) {
            url
          }
        }
        mobileImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
      }
    }
  }
  keywords: fieldPKeywords{
    entity{
    keyword: entityLabel
      url: entityUrl{
        path
      }
    }
  }
  description: fieldPFilterDescription{
    processed
  }
  contentLink: entityUrl{
    routed
    path
  }
  footerText: fieldCardFooterLabel
}

fragment FieldScheduledEventCardsQueue on NodeScheduledEvent {
  image: fieldSeFeaturedImage {
    entity {
      ... on MediaImage {
        desktopImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
        tabletImg: fieldMediaImage {
          derivative(style: CARDHORIZONTAL) {
            url
          }
        }
        mobileImg: fieldMediaImage {
          derivative(style: CARDVERTICAL) {
            url
          }
        }
      }
    }
  }
  contentLink: entityUrl{
    path
  }
  venue: fieldSeVenue

  keywords: fieldSeKeywords {
    entity {
      keyword: entityLabel
        url: entityUrl {
        path
      }
    }
  }
  dateRange: fieldSeDateRange{
    value
    startDate
    endValue
    endDate
  }
  description: fieldSeDescription{
    processed
  }
}