fragment TranslatedDocuments on ParagraphTranslatedDocuments {
  title: fieldTitle
  partOfNavigator: fieldPartOfNavigatorSidebar
  translatedDocuments: fieldPtdTranslations {
    translatedDocument: entity {
      ... on MediaTranslation {
        name: name
        english: fieldMtEnglishTitle
        translated: fieldMtTranslatedTitle
        media: fieldMediaFile {
          file: entity {
            ... on File {
              url
            }
          }
        }
      }
    }
  }
}