fragment WhatsRelated on ParagraphWhatsRelated {
  title: fieldTitle
  chapterLink: fieldChapterLinkOnCard
  partOfNavigator: fieldPartOfNavigatorSidebar
  relatedLinks: fieldPwrRelatedContent {
    links: entity {
      label: entityLabel
      type: entityType
      ... on MediaDocument {
        fieldDocument {
          file: entity {
            ... on File {
              entityLabel
              url
            }
          }
        }
      }
      ... on NodeArticlePage {
        contentLink: entityUrl {
          path
        }
      }
      ... on NodeEmergency {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeExecutiveOrder {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeGovernorPhotos {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeLegislation {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeLandingPage {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeNews {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeProgram {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeScheduledEvent {
        contentLink: entityUrl{
          path
        }
      }

      ... on NodeService {
        contentLink: entityUrl{
          path
        }
      }
    }
  }
}
