fragment ServiceCategoriesTerm on TaxonomyTermServiceCategories {
  serviceTerm: name
  sections: fieldSections{
    section: entity {
			type: __typename
			bundle: entityBundle
			...WYSIWYG
      ...CardsQueue
		}
  }
}