fragment CountyTerm on TaxonomyTermCounty {
  taxonomyType: entityBundle
  featuredImage: fieldImage {
		entity {
			... on MediaImage {
				desktopImg: fieldMediaImage {
					derivative(style: HEROWIDE) {
						url
					}
				}
				tabletImg: fieldMediaImage {
					derivative(style: HERONARROW) {
						url
					}
				}
				mobileImg: fieldMediaImage {
					derivative(style: HEROMOBILE) {
						url
					}
				}
			}
		}
	}
	region: fieldRegion {
		entity {
			keyword: entityLabel
		  entityUrl {
				path
			}
		}
	}
  title: name
  area:fieldCountyArea
  founded:fieldCountyFounded
  population:fieldCountyPopulation
  contentType: entityBundle
  sections: fieldSections {
    section: entity {
      type: __typename
      ...WYSIWYG
      ...Contact
      ...Documents
      ...PhotoGallery
      ...TranslatedDocuments
      ...Quote
      ...VideoEmbed
    }
  }
}