<!-- <div id="ux-domain-menu"> -->
          <div class="agency-name"><a href="https://labor.ny.gov" aria-label="Link to Agency Department of Labor Page.">Department of Labor</a></div> <!-- Link back to Agency site homepage. -->
	<div class="main-page"></div> <!-- Link back to the page on the agency site that leads the user here. -->
	
	<div class="application-name"></div>
          <!-- </div> -->
        </div>
      </div>
    </header>
    <div class="gov-bar-fix">
      <div id="ux-page" class="group">
        <div class="container_16 ux-content clearfix">

          <noscript>
            <div class="grid_16">
              <p class=" ux-msg warning margin-bottom-none">
                <strong>JavaScript is currently disabled in your web browser. </strong>
                <br />For full functionality of this site, it is necessary to enable JavaScript. Here are <a href="http://www.enable-javascript.com/" target="_blank">
              instructions how to enable JavaScript</a>.
                <p>
            </div>
          </noscript>
