<!-- <div id="ux-domain-menu"> -->
          <div class="agency-name"><a href="https://labor.ny.gov" aria-label="Link to Agency Department of Labor Page.">Department of Labor</a></div> <!-- Link back to Agency site homepage. -->
	<div class="main-page"></div> <!-- Link back to the page on the agency site that leads the user here. -->
	
	<div class="application-name"></div>
          <!-- </div> -->
        </div>
      </div>
    </header>

