<link rel="stylesheet" media="screen" href="//www.labor.ny.gov/css/apps/css/ux-internet-content-utility-v.0.5.0.css">
    <!-- JS -->
    <script src="/css/v.0.5.0/js/modernizr.min.js"></script>
    <!--[if (IE 8)|(IE 7)]><script src="/css/v.0.5.0/js/respond.min.js"></script><![endif]-->
    <script src="https://www.google.com/jsapi"></script>
	<link rel="stylesheet" type="text/css" href="/includes/ux_template_upgrade/css/styles.css">
  </head>

  <!--[if IE 7 ]>    <body class="ie7 "> <![endif]-->
  <!--[if IE 8 ]>    <body class="ie8 "> <![endif]-->
  <!--[if IE 9 ]>    <body class="ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!-->

  <body class="ux-website">
    <!--<![endif]-->

    <header class="group">

