      <div id="ux-notification-container">
        <div class="ux-content-wrapper">
          <div id="ux-action-required-notifications" class="ux-notice-outer">
            <div class="arn-tray ux-notice-inner">
            </div>
          </div>
          <div id="ux-generic-notifications">
          </div>
        </div>
      </div>
                      
      <div id="nygov-universal-navigation" class="nygov-universal-container" data-iframe="true">
        <noscript>
          <iframe width="100%" height="86px" src="//static-assets.ny.gov/load_global_menu/ajax?iframe=true" frameborder="0" style="border:none; overflow:hidden; width:100%; height:86px;" scrolling="no">
            Your browser does not support iFrames
          </iframe>
        </noscript>
        <script type="text/javascript">
          var _NY = {
            HOST: "static-assets.ny.gov",
            BASE_HOST: "www.ny.gov",
            hideSettings: false,
            hideSearch: false
          };
          (function(document, bundle, head) {
            head = document.getElementsByTagName('head')[0];
            bundle = document.createElement('script');
            bundle.type = 'text/javascript';
            bundle.async = true;
            bundle.src = "//static-assets.ny.gov/sites/all/widgets/universal-navigation/js/dist/global-nav-bundle.js";
            head.appendChild(bundle);
          }(document));

        </script>
      </div>
      <div id="ux-site-header">
        <div class="nys-global-header horizontal unstacked">
          <div class="nav-toggle">
            <a href="#" role="button" id="nys-menu-control">Navigation menu</a>
          </div>
<!--Text for h1 (denoting state agency) in header3.inc-->