	<!-- App template footer -->
		<div class="footer">
	<div class="agency-name-footer"><a href="https://labor.ny.gov" aria-label="Link to Agency Home Page.">Department of Labor</a></div>
	<div class="hrule"></div>
	<div class="footer-links-first"><a href="https://labor.ny.gov/agencyinfo/accessibility.shtm" aria-label="Link to Agency's Accessibility statement.">Accessibility</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov/dol-contact.shtm" aria-label="Link to our Contact information..">Contact</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Agency's Web Site Disclaimer.">Disclaimer</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov/immigrants/language-access-complaint.shtm" aria-label="Link to the Agency's Language Access information.">Language Access</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov/privacy.shtm" aria-label="Link to the Agency's Privacy statement.">Privacy Policy</a></div>

	<!-- Replace "xxYOUR-IDxx" in the URLs below with the applicable ID from your social media accounts. Comment out any that do not apply. -->
	<div class="social">
		<div class="social-icons"><a href="http://www.facebook.com/nyslabor" title="Facebook" aria-label="Visit us on Facebook."><span class="icon-facebook"></span></a></div>
		<div class="social-icons"><a href="http://twitter.com/nyslabor" title="Twitter" aria-label="Visit us on Twitter."><span class="icon-twitter"></span></a></div>
		<div class="social-icons"><a href="http://instagram.com/nyslabor" title="Instagram" aria-label="Visit us on Instagram."><span class="icon-instagram"></span></a></div>
	</div>
</div>
		<!-- End App template footer -->
		<script data-main="true" src="//www.labor.ny.gov/css/apps/<!--#include virtual="/includes/ux_template_upgrade/ux_template_version.inc"-->/js/ux-script.min.js"></script>
		<script src="//www.labor.ny.gov/css/apps/<!--#include virtual="/includes/ux_template_upgrade/ux_template_version.inc"-->/js/nys-global-nav-header.min.js"></script>
		<script src="//www.labor.ny.gov/css/apps/js/ux-internet-content-utility-v.0.4.12.js"></script>
		<script>     
		$(document).ready(function() {
         	ux.load("jqueryDialog");
		});  
		</script> 
		<script type="text/javascript" src="js/regional.js"></script>

		