					<div id="ux-page-rating" class="grid_12">
						<div id="ratings" class="group margin-bottom" data-type="insert" data-key="">
							<p>
								<span class="title h6">This Page...</span>
								<a class="upvote" href="#">
									<span class="text" >Was Helpful</span>
								</a>
								<a class="downvote" href="#">
									<span class="text" >Needs Improvement</span>
								</a>
							</p>
						</div>
						<div class="grid_7 group" id="additional-info">
							<form id="written-feedback" class="ux-form-top">
								<label>	
									<span>
										What could be improved?
									</span>
									<textarea name="comment"></textarea>
								</label>
								<div id="rating-submit">
									<input type="button" id="feedBackSubmit" class="button_mini no-icon primary" value="Send Feedback" />
									<a href="#" class="no-comment">Don't leave comment</a>
								</div>
							</form>
							<p id="pr-thank-you" class="h6 title ux-msg-inline success">
								<span>Thanks for the feedback!  It will help us improve your experience.</span>
							</p>
						</div>
					</div>		


				</div>
			</div>
		</div>
		</div>
		<!-- App template footer -->
		<div class="footer">
	<div class="agency-name-footer"><a href="https://labor.ny.gov" aria-label="Link to Agency Home Page.">Department of Labor</a></div>
	<div class="hrule"></div>
	<div class="footer-links-first"><a href="https://labor.ny.gov/agencyinfo/accessibility.shtm" aria-label="Link to Agency's Accessibility statement.">Accessibility</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov/dol-contact.shtm" aria-label="Link to our Contact information..">Contact</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Agency's Web Site Disclaimer.">Disclaimer</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov/immigrants/language-access-complaint.shtm" aria-label="Link to the Agency's Language Access information.">Language Access</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov/privacy.shtm" aria-label="Link to the Agency's Privacy statement.">Privacy Policy</a></div>

	<!-- Replace "xxYOUR-IDxx" in the URLs below with the applicable ID from your social media accounts. Comment out any that do not apply. -->
	<div class="social">
		<div class="social-icons"><a href="http://www.facebook.com/nyslabor" title="Facebook" aria-label="Visit us on Facebook."><span class="icon-facebook"></span></a></div>
		<div class="social-icons"><a href="http://twitter.com/nyslabor" title="Twitter" aria-label="Visit us on Twitter."><span class="icon-twitter"></span></a></div>
		<div class="social-icons"><a href="http://instagram.com/nyslabor" title="Instagram" aria-label="Visit us on Instagram."><span class="icon-instagram"></span></a></div>
	</div>
</div>
		<!-- End App template footer -->
		<script data-main="true" src="//www.labor.ny.gov/css/apps/<!--#include virtual="/includes/ux_template_upgrade/ux_template_version.inc"-->/js/ux-script.min.js"></script>
		<script src="//www.labor.ny.gov/css/apps/<!--#include virtual="/includes/ux_template_upgrade/ux_template_version.inc"-->/js/nys-global-nav-header.min.js"></script>
		<script src="//www.labor.ny.gov/css/apps/js/ux-internet-content-utility-v.0.4.12.js"></script>