fragment AgencyTerm on TaxonomyTermAgency {
  taxonomyType: entityBundle
	logo: fieldTaLogo {
		entity {
			... on MediaImage {
				img: fieldMediaImage {
					derivative(style: THUMBNAIL) {
						url
					}
				}
			}
		}
	}
	featuredImage: fieldTaFeaturedImage {
		entity {
			... on MediaImage {
				desktopImg: fieldMediaImage {
					derivative(style: HEROWIDE) {
						url
					}
				}
				tabletImg: fieldMediaImage {
					derivative(style: HERONARROW) {
						url
					}
				}
				mobileImg: fieldMediaImage {
					derivative(style: HEROMOBILE) {
						url
					}
				}
			}
		}
	}
	title: entityLabel
	category: fieldTaAgencyCategory {
		entity {
			keyword: entityLabel
			url: entityUrl {
				path
			}
		}
	}
	website: fieldTaAgencyWebsite {
		linkText: title
		url {
			path
		}
	}
  sections: fieldSections{
    section: entity {
			type: __typename
			bundle: entityBundle
      ...WYSIWYG
      ...Contact
      ...Documents
      ...PhotoGallery
      ...TranslatedDocuments
      ...Quote
      ...VideoEmbed
		}
  }
}