		</div>
	</div> <!-- end #content -->
</div>	 <!-- end #page-wrap -->

<div id="dol-footer">
	<div id="dol-footer-inner" class="container_12">
	<!-- begin global footer area -->

		<ul id="global-footer-menu">
			<li><a href="http://www.labor.ny.gov/agencyinfo/aicontactus.shtm" target="_blank">Contact Us</a></li>
			<li><a href="http://www.labor.ny.gov/agencyinfo/accessibility.shtm" target="_blank">Accessibility Policy</a></li>
			<li><a href="http://www.labor.ny.gov/privacy.shtm" target="_blank">Privacy Policy</a></li>
			<li><a href="http://www.adobe.com/accessibility/products/reader/" target="_blank">Get Adobe Reader</a></li>
		</ul>
	<!-- end global footer area -->
	</div>
</div> <!-- end #footer -->
<script>var ux_NavOutWarning = false;</script>
<script type="text/javascript" src="http://www.labor.ny.gov/css/apps/v.0.3.1/js/ux-script.min.js"></script>

<!--[if (gt IE 6)|!(IE)]><!--> 
	<script src="//www.labor.ny.gov/css/apps/ux-data/menu.js"></script>
	<script src="http://www.labor.ny.gov/css/apps/v.0.3.1/js/mega-menu.min.js"></script>
<!--<![endif]-->