			<div id="ux-notification-container">
				<div class="ux-content-wrapper">
					<div id="ux-action-required-notifications" class="ux-notice-outer">
						<div class="arn-tray ux-notice-inner">
						</div>
					</div>
					<div id="ux-generic-notifications">
					</div>
				</div>
			</div>

			<iframe id="nygov-universal-navigation-frame" class="nygov-universal-container" width="100%" height="86px" src="//static-assets.ny.gov/load_global_menu/ajax?iframe=true&target=blank" data-updated="2014-11-07 08:30" frameborder="0" style="border:none; overflow:hidden; width:100%; height:86px;" scrolling="no">
            			Your browser does not support iFrames
			</iframe>
			<!-- Google Tag Manager -->
    				<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-T4FP6H" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    				<script type="text/javascript">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0];var j=d.createElement(s);var dl=l!='dataLayer'?'&l='+l:'';j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;j.type='text/javascript';j.async=true;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-T4FP6H');</script>
			<!-- End Google Tag Manager -->
			<div id="ux-site-header">
				<div class="container_16 ux-content">
					<a href="https://labor.ny.gov" id="ux-site-logo">
						<h1>
							<span class="ux-hide-508">New York State Department of Labor</span>
						</h1>
					</a>
					<span id="ux-site-title">