	<script src="https://www.labor.ny.gov/css/apps/<!--#include virtual="/includes/ux_template/ux_template_version.inc"-->/js/modernizr.min.js"></script>
	<link rel="stylesheet" type="text/css" href="../css/styles.css">
</head>
    <!--[if lt IE 7 ]> <body class=" ie6 ux-website"> <![endif]-->
    <!--[if IE 7 ]>    <body class=" ie7 ux-website"> <![endif]-->
    <!--[if IE 8 ]>    <body class=" ie8 ux-website"> <![endif]-->

    <!--[if IE 9 ]>    <body class=" ie9 ux-website"> <![endif]-->
    <!--[if (gt IE 9)|!(IE)]><!--> 
	<body class=" ux-website" >
	<!--<![endif]-->