<div class="footer">
	<div class="agency-name-footer"><a href="https://labor.ny.gov" aria-label="Link to Agency Home Page.">Department of Labor</a></div>
	<div class="hrule"></div>
	<div class="footer-links-first"><a href="https://labor.ny.gov" aria-label="Link to Agency's Accessibility statement.">Accessibility</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to our Contact information..">Contact</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Agency's Web Site Disclaimer.">Disclaimer</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Agency's Language Access information.">Language Access</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Agency's Privacy statement.">Privacy Policy</a></div>

	<!-- Replace "xxYOUR-IDxx" in the URLs below with the applicable ID from your social media accounts. Comment out any that do not apply. -->
	<div class="social">
		<div class="social-icons"><a href="https://facebook.com/xxYOUR-IDxx" title="Facebook" aria-label="Visit us on Facebook."><span class="icon-facebook"></span></a></div>
		<div class="social-icons"><a href="https://twitter.com/xxYOUR-IDxx" title="Twitter" aria-label="Visit us on Twitter."><span class="icon-twitter"></span></a></div>
		<div class="social-icons"><a href="https://instagram.com/xxYOUR-IDxx" title="Instagram" aria-label="Visit us on Instagram."><span class="icon-instagram"></span></a></div>
	</div>
</div> <!-- end #footer -->

	<script src="//labor.ny.gov/css/apps/<!--#include virtual="/includes/ux_template/ux_template_version.inc"-->/js/ux-script.min.js"></script>
	<script src="/css/apps/js/ux-internet-content-utility.js?20130807A"></script>