</div>

	
	 			<div id="site-wide-search">
					<form name="_ipsubmit" id="search-box-form" method="get" action="http://search.cio.ny.gov/search" autocomplete="off">
						<label for="q" id="search-label" class="accessibility-text">Search Department of Labor:</label>
						<input type="text" id="q" name="q" value="" size="21" title="Input Search" class="text_box site-wide-search-text-box" placeholder="Search DOL" autocomplete="off" />
						<input type="submit" title="Submit Search" value="GO" name="submit" class="submit site-wide-search-button accessibility-text" id="search-submit" />
						<input type="hidden" name="entqr" value="0" />
						<input type="hidden" name="ud" value="1" />
						<input type="hidden" name="sort" value="date:D:L:d1" />

						<input type="hidden" name="output" value="xml_no_dtd" />
						<input type="hidden" name="oe" value="UTF-8" />
						<input type="hidden" name="ie" value="UTF-8" />
						<input type="hidden" name="client" value="labor_frontend" />
						<input type="hidden" name="proxystylesheet" value="labor_frontend" />
						<input type="hidden" name="site" value="labor_collection" /> 
					</form>
	 			</div>
		
 	<header>
	<div class="agency-name"><a href="https://labor.ny.gov" aria-label="Link to Agency Home Page.">Department of Labor</a></div> <!-- Link back to Agency site homepage. -->
	<div class="main-page"><a href="https://labor.ny.gov/stats" aria-label="Link back to page where the application was introduced.">Labor Statistics</a></div> <!-- Link back to the page on the agency site that leads the user here. -->
	<span class="icon-play"></span>
	<div class="application-name">Research and Statistics</div>
</header>
	
</div> 

<div id="page-wrap" class="group">
	<div id="content" class="container_16 group">
				<noscript>
					<div class="grid_16">
					<p class=" ux-msg warning margin-bottom-none">
						<strong>JavaScript is currently disabled in your web browser. </strong> 
							<br />For full functionality of this site, it is necessary to enable JavaScript. 
							Here are <a href="http://www.enable-javascript.com/" target="_blank">
 							instructions how to enable JavaScript</a>.
					<p>
					</div>	
				</noscript>
		