fragment Biography on ParagraphBiography {
  partOfNavigator: fieldPartOfNavigatorSidebar
	title: fieldTitle
  bioImage: fieldBioImage {
    entity {
      ... on MediaImage {
        bioImg: fieldMediaImage {
          derivative(style: BIOGRAPHY) {
            url
          }
        }
      }
    }
  }
  bioName: fieldBioName
  bioTitle: fieldBioTitle
  dateOfBirth: fieldBioDateOfBirth
  dateOfDeath: fieldBioDateOfDeath
  textFirst: fieldBioText1 {
    content: processed
  }
  bioQuote: fieldBioQuote
  bioQuoteCredit: fieldBioQuoteCredit
  textSecond: fieldBioText2 {
    content: processed
  }
  video: fieldBioVideo
  textThird: fieldBioText3 {
    content: processed
  }
  bioLinkTitle: fieldBioLinkTitle
  bioLink: fieldBioLink {
    url {
      path
    }
    title
  }
}
