fragment Highlight on ParagraphHighlight {
  image: fieldPhImage{
    entity{
      ... on MediaImage {
        highlightImage: fieldMediaImage {
          alt
          derivative (style:SQUAREEXTRALARGE){
            url
          }
        }
      }
    }
  }
  title: fieldTitle
  headline: fieldHeadline
  subtitle: fieldPhSubtitle
  description: fieldDescription{
    processed
  }
  link: fieldLink{
    title
    url{
      path
    }
  }
  newWindowToggle: fieldOpenInNewWindow
}