fragment NewsPage on NodeNews {
  contentType: entityBundle
  dateOption: fieldNDateToggle
  dateCreated: entityCreated
  title
  contentSubheadline: fieldNSubHeadline {
    processed
  }
  featuredImage: fieldNFeaturedImage {
    entity {
      ... on MediaImage {
        desktopImg: fieldMediaImage {
          derivative(style: HEROWIDE) {
            url
          }
        }
        tabletImg: fieldMediaImage {
          derivative(style: HERONARROW) {
            url
          }
        }
        mobileImg: fieldMediaImage {
          derivative(style: HEROMOBILE) {
            url
          }
        }
      }
    }
  }
  location: fieldNLocation
  keywords: fieldNKeywords {
    entity {
      keyword: entityLabel
      url: entityUrl {
        path
      }
    }
  }
  sections: fieldSections {
    section: entity {
      type: __typename
      ...WYSIWYG
      ...Contact
      ...Documents
      ...PhotoGallery
      ...TranslatedDocuments
      ...Quote
      ...VideoEmbed
      ...AudiosPhotosButtons
      ...JazzedRelease
		}
	}
}
