fragment ProgramSupporter on ParagraphProgramSupporter {
  title: fieldTitle
  headline: fieldHeadline
  seemore: fieldPpsSeeMore {
    uri
    title
  }
  color: fieldPpsColorOption
  supporterParagraphs: fieldPpsSupporters {
    paragraph: entity{
      ... on ParagraphSupporter {
        name: fieldPsName
        title: fieldPsTitle
        quote: fieldPsQuote
        facebook: fieldSupporterFacebook {
          uri
        }
        twitter: fieldSupporterTwitter {
          uri
        }
        image:  fieldPsPhoto {
          entity {
            ... on MediaImage {
              desktopImg: fieldMediaImage {
                derivative(style: COVERIMAGE660X400) {
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}
