<!-- This is the best placement for the Universal Navigation, find instructions here https://github.com/ny/universal-navigation -->
<body>
 <div id="nygov-universal-navigation" class="nygov-universal-container" data-iframe="true" data-updated="2014-11-07 08:30">
    <noscript>
        <iframe width="100%" height="86px" src="//static-assets.ny.gov/load_global_menu/ajax?iframe=true" frameborder="0" style="border:none; overflow:hidden; width:100%; height:86px;" scrolling="no">
            Your browser does not support iFrames
        </iframe>
    </noscript>
    <script type="text/javascript">
        var _NY = {
            HOST: "static-assets.ny.gov",
            BASE_HOST: "www.ny.gov",
            hideSettings: false,
            hideSearch: false
        };
        (function (document, bundle, head) {
            head = document.getElementsByTagName('head')[0];
            bundle = document.createElement('script');
            bundle.type = 'text/javascript';
            bundle.async = true;
            bundle.src = "//static-assets.ny.gov/sites/all/widgets/universal-navigation/js/dist/global-nav-bundle.js";
            head.appendChild(bundle);
        }(document));
    </script>
</div>
<header>
	<div class="agency-name"><a href="https://labor.ny.gov" aria-label="Link to Agency Department of Labor Page.">Department of Labor</a></div> <!-- Link back to Agency site homepage. -->
	<div class="main-page"><a href="https://labor.ny.gov"/stats aria-label="Link back to page where the application was introduced.">Department of Labor Statistics</a></div> <!-- Link back to the page on the agency site that leads the user here. -->
	<span class="icon-play"></span>
	<div class="application-name">Research and Statistics</div>
</header>