<div class="footer">
	<div class="agency-name-footer"><a href="https://labor.ny.gov" aria-label="Link to Department of Labor Home Page.">Department of Labor</a></div>
	<div class="hrule"></div>
	<div class="footer-links-first"><a href="https://labor.ny.gov/agencyinfo/accessibility.shtm" aria-label="Link to Department of Labor's Accessibility statement.">Accessibility</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov/dol-contact.shtm" aria-label="Link to our Contact information..">Contact</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Department of Labor's Web Site Disclaimer.">Disclaimer</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Department of Labor's Language Access information.">Language Access</a></div>
	<div class="footer-links"><a href="https://labor.ny.gov" aria-label="Link to the Department of Labor's Privacy statement.">Privacy Policy</a></div>

	<!-- Replace "xxYOUR-IDxx" in the URLs below with the applicable ID from your social media accounts. Comment out any that do not apply. -->
	<div class="social">
		<div class="social-icons"><a href="http://www.facebook.com/nyslabor" title="Facebook" aria-label="Visit us on Facebook."><span class="icon-facebook"></span></a></div>
		<div class="social-icons"><a href="http://twitter.com/nyslabor" title="Twitter" aria-label="Visit us on Twitter."><span class="icon-twitter"></span></a></div>
		<div class="social-icons"><a href="http://www.youtube.com/user/NYSLabor" title="YouTube" aria-label="Visit us on YouTube."><span class="icon-youtube"></span></a></div>
		<div class="social-icons"><a href="http://instagram.com/nyslabor" title="Instagram" aria-label="Visit us on Instagram."><span class="icon-instagram"></span></a></div>
		<div class="social-icons"><a href="https://www.linkedin.com/company/new-york-state-department-of-labor" title="LinkedIn" aria-label="Visit us on LinkedIn."><span class="icon-linkedin"></span></a></div>
	</div>
</div>
<script type='text/javascript'>
(function(){var g=function(e,h,f,g){
this.get=function(a){for(var a=a+"=",c=document.cookie.split(";"),b=0,e=c.length;b<e;b++){for(var d=c[b];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null};
this.set=function(a,c){var b="",b=new Date;b.setTime(b.getTime()+6048E5);b="; expires="+b.toGMTString();document.cookie=a+"="+c+b+"; path=/; "};
this.check=function(){var a=this.get(f);if(a)a=a.split(":");else if(100!=e)"v"==h&&(e=Math.random()>=e/100?0:100),a=[h,e,0],this.set(f,a.join(":"));else return!0;var c=a[1];if(100==c)return!0;switch(a[0]){case "v":return!1;case "r":return c=a[2]%Math.floor(100/c),a[2]++,this.set(f,a.join(":")),!c}return!0};
this.go=function(){if(this.check()){var a=document.createElement("script");a.type="text/javascript";a.src=g+ "&t=" + (new Date()).getTime();document.body&&document.body.appendChild(a)}};
this.start=function(){var a=this;window.addEventListener?window.addEventListener("load",function(){a.go()},!1):window.attachEvent&&window.attachEvent("onload",function(){a.go()})}};
try{(new g(100,"r","QSI_S_ZN_6eSONGWExC3sowR","//zn_6esongwexc3sowr-rga.siteintercept.qualtrics.com/WRSiteInterceptEngine/?Q_ZID=ZN_6eSONGWExC3sowR&Q_LOC="+encodeURIComponent(window.location.href))).start()}catch(i){}})();
</script><div id='ZN_6eSONGWExC3sowR'><!--DO NOT REMOVE-CONTENTS PLACED HERE--></div>	
	<iframe id="nygov-universal-footer-frame" class="nygov-universal-container" width="100%" height="200px" src="//static-assets.ny.gov/load_global_footer/ajax?iframe=true&target=blank" data-updated="2014-11-07 08:30" frameborder="0" style="border:none; overflow:hidden; width:100%; height:200px;" scrolling="no">
            Your browser does not support iFrames
        </iframe>
</body>
</html>
