
			
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">Labor Statistics</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Labor Statistics Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/green/index.shtm">Green Jobs Survey</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/prlaus.shtm">Monthly Press Release - Local Area Unemployment Rates</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">Monthly Press Release - Statewide Jobs Data</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Workforce Innovation and Opportunity Act</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/lwia.shtm">Local Workforce Development Boards</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforce/swib/SWIBAbout.shtm">State Workforce Investment Board</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Legal</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/adjudication-decisions.shtm">Adjudication Decisions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/counsel-opinion-letters.shtm">Counsel Letters</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Frequently Asked Questions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/legal-updates.shtm">Legal Updates</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Public Work</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Overview</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/wpp/publicViewPWChanges.do?method=showIt">Article 8 - Construction</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/wpp/publicViewPWChangesArt9.do?method=showIt">Article 9 - Building Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWDebarmentInformation.shtm">Debarred List</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="http://labor.ny.gov/nys-data-center/index.shtm">New York State Data Center</a>
						</li>
						<li>
							<a href="http://labor.ny.gov/data-sharing/">Unemployment Insurance Data Sharing</a>
						</li>
					</ul>
				</nav>
			</div>
