<ul>
	<li><a href="http://labor.ny.gov/stats/index.shtm">Labor Statistics</a></li>
	<li><a href="http://labor.ny.gov/workforcenypartners/lwda.shtm">Local Workforce Development Boards</a></li>
	<li><a href=" http://labor.ny.gov/nys-data-center/index.shtm">State Data Center </a></li>
	<li><a href="http://labor.ny.gov/workforcenypartners/tools.shtm">Programs &amp; Tools for Workforce Professionals </a></li>
	<li><a href="http://labor.ny.gov/workforce/swib/SWIBAbout.shtm">State Workforce Development Board</a></li>
	<li><a href="http://labor.ny.gov/data-sharing/">Unemployment Insurance Data Sharing</a></li>
</ul>