
			
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">Job Seekers</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Job Seekers</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/career-center-events.shtm">Career Center Events</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/career-center-events.shtm">Career Fairs and Recruitments</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/CareerServicesIndex.shtm">Find a Job</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/career-center-locator/">New York State Career Centers</a>
											</li>
<li><a href="http://labor.ny.gov/careerservices/special-services.shtm">Special Services and Health Insurance</a></li>
											<li>
												<strong >Apprenticeship</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/registration.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/occupations.shtm">Active Trades</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/pressreleases/apprenticeshiparchive.shtm">Current Recruitments</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Career Development</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/planyourcareer/planningyourcareerindex.shtm">Overview</a>
											</li>
											<li>
												<a href="http://www.careerzone.ny.gov/">CareerZone</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/jobzone/index.shtm">JobZone</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lstrain.shtm">Occupational Licenses and Certifications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/findajob/res_fun.shtm">Resumes</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/planyourcareer/training.shtm">Training</a>
											</li>
                                       							<li>
												<a href="https://applications.labor.ny.gov/ETPL/">Training Provider List</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Labor Statistics</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lscesmaj.shtm">Current Employment Statistics</a>
											</li>
											<li>
												<a href="http://www.labor.ny.gov/stats/lsproj.shtm">Growing Occupations</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">Monthly Jobs Press Release</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Occupational Wages</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Unemployment</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Online Services</strong>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Check Payment History</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Claim Weekly Benefits</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">File a Claim</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Print 1099</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Register for Direct Deposit</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Important Links</strong>
											</li>
											
											
											<li>
												<a href="http://labor.ny.gov/agencyinfo/report-fraud.shtm">Report Fraud</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/unemploymentassistance.shtm">Unemployment Assistance</a>
											</li>
                                                                                        <li>
												<a href="http://labor.ny.gov/workforcenypartners/warn/warnportal.shtm">WARN Notices</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Important Documents</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/claimantinfo/Claimant%20Handbook%20-%20Languages.shtm">Claimant Handbook</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/claimant-forms-and-publications.shtm">Forms and Publications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/faq.shtm">Frequently Asked Questions</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Workers</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Wages/Breaks</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/meals.shtm">Breaks</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minwage.shtm">Minimum Wage</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/nursing-mothers.shtm">Nursing Mothers in the Workplace</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/faq.shtm#4">Overtime</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/posters.shtm">Required Posters</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Wage Rates</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Paid Family Leave</strong>
											</li>
											<li>
												<a href="//www.ny.gov/paidfamilyleave">Overview</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Public Work</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Overview</a>
											</li>
											<li>
												<a href="https://apps.labor.ny.gov/wpp/publicViewPWChanges.do?method=showIt">Article 8 - Construction</a>
											</li>
											<li>
												<a href="https://apps.labor.ny.gov/wpp/publicViewPWChangesArt9.do?method=showIt">Article 9 - Building Services</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Safety and Health</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_INDEX.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_PESH.shtm">Public Employee Safety & Health</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/safe-patient-handling.shtm">Safe Patient Handling</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/workplaceviolence.shtm">Workplace Violence Prevention</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Equal Opportunity</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/how-to-file-a-discrimination-claim.shtm">File a Discrimination Complaint</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong>Work For Success</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/work-for-success/">Work For Success Program Overview</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Youth</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="https://labor.ny.gov/youth">Information Portal</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minors.shtm">Child Labor Law</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/secure/child_index.shtm">Child Performer</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/wphmpg.shtm">Working Papers</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Veterans</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/vets/vetintropage.shtm">Veterans' Services</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Immigrants</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Division of Immigrant Policies and Affairs</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Legal Updates</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/legal-updates.shtm">Legal Updates</a>
											</li>
											<li>
												<a href="//www.ny.gov/paidfamilyleave">Paid Family Leave</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
	