
			
			<div class="sub-nav outer-sub-nav">

				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">Unemployment Insurance</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employer.shtm">Employer Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/employer-handbooks.shtm">Employer Handbooks</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/Authentication/index.shtm">Unemployment Insurance Online Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/registering-for-unemployment-insurance.shtm">Registering</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/sides-overview.shtm">Unemployment Insurance State Information Data Exchange System (SIDES)</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/interest-assessment-surcharge.shtm">Interest Assessment Surcharge</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/quarterly-reporting.shtm">Quarterly Reporting</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://www.labor.ny.gov/ui/employerinfo/ui-rate-information.shtm">UI Rate Information</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/employer-forms-publications.shtm">Forms and Publications</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/shared-work-program.shtm">The Shared Work Program</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/agencyinfo/report-fraud.shtm">Report Fraud</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Business Services</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
								    <div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/businessservices/landing.shtm">Overview</a>
											</li>
											<li>
												<a href="https://www.businessexpress.ny.gov" target="_blank">New York Business Express</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Recruitment Services</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/lookforworkers/lookingforworkersIndex.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/job-fairs.shtm">Career Fairs and Recruitments</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/services/perm.shtm">Place a Job Order</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Manage Your Workforce</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/services/servicesindex.shtm">Consultation Services</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/ETPL/">Eligible Training Providers</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/funding.shtm">Funding Opportunities</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/immigrants/agriculture-labor-program/services-for-agriculture-employers.shtm">Services for Agricultural Employers</a>
											</li>
											<li>
												<a href="//www.ny.gov/paidfamilyleave">Paid Family Leave</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Hiring Incentives</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/services/fbp.shtm">Federal Bonding Program</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/youth-tax-credit.shtm">Urban Youth Jobs/New York Youth Jobs Program</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/ojt.shtm">On-the-Job Training</a>
											</li>
											<li>
												<a href="http://www.labor.ny.gov/careerservices/work-for-success/">Work For Success Program</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/edsu/edsu%20wotc.shtm">Work Opportunity Tax Credit (WOTC)</a>
											</li>
<li><a href="http://labor.ny.gov/businessservices/edsu/edsu%20wetc.shtm">Workers Employment Tax Credit (WETC)</a></li>
<li><a href="http://labor.ny.gov/businessservices/disability-tax-credit.shtm">Workers with Disabilities Tax Credit (WDTC)</a></li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Apprenticeship</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/appsponsor.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/sponsor/index.asp">Active Sponsors List</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/atc.shtm">Apprenticeship and Training Council</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/activesponsorlist.shtm#dereg">Deregistered/Closed Programs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/lawsandregs.shtm">Laws and Regulations</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/pending-approval.shtm">Programs Pending Approval</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Labor Statistics</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lseeo.shtm">Affirmative Action Data</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Occupational Wages</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Labor Law</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/adjudication-decisions.shtm">Adjudication Decisions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minors.shtm">Child Labor</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/secure/foilrequest.shtm">FOIL Requests</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Legal Frequently Asked Questions</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/counsel-opinion-letters.shtm">Legal Opinions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/legal-updates.shtm">Legal Updates</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWGeneralProvisions.shtm">Public Work - General Provisions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/warn/warnportal.shtm">WARN Notices</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Worker Protection</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Labor Standards</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/labor_standards.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/garment.asp">Apparel Industry</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/farm_labor.shtm">Farm Labor</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Immigrants and Non-English Speakers</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/wpcpu.shtm">Licenses, Permits, Certifications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/posters.shtm">Required Posters</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Safety & Health</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_INDEX.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_BOARDS.shtm">Boards and Councils</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_CODE_RULES.shtm">Codes and Regulations</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_PROGRAMS.shtm">Special Programs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/workplaceviolence.shtm ">Workplace Violence Prevention</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Wages/Breaks</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/meals.shtm">Breaks</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minwage.shtm">Minimum Wage</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/faq.shtm#4">Overtime</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Wage Rates</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Public Work</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Overview</a>
											</li>
											<li>
												<a href="https://apps.labor.ny.gov/wpp/publicViewPWChanges.do?method=showIt">Article 8 - Construction</a>
											</li>
											<li>
												<a href="https://apps.labor.ny.gov/wpp/publicViewPWChangesArt9.do?method=showIt">Article 9 - Building Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWDebarmentInformation.shtm">Debarred List</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Online Services</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="https://wps.labor.state.ny.us/WPS_Curam/en/WPEmployer_ExternalhomePage.do">Asbestos Notifications</a>
											</li>
											<li>
												<a href="https://www.businessexpress.ny.gov/app/answers/cms/a_id/3033/kw/NYS%20100">NYS-100 Business Employer Registration Form</a>
											</li>
                                                                                        <li>
												<a href="https://www.businessexpress.ny.gov/app/answers/cms/a_id/3036/kw/NYS%20100%20Household">NYS-100 Household Employer Registration Form</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/Authentication/index.shtm">Unemployment Insurance Online Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/Authentication/index.shtm">File a Quarterly Report (NYS-45)</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Immigrants</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Division of Immigrant Policies and Affairs</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
		