<ul>
	<li><a href="http://labor.ny.gov/unemploymentassistance.shtm">Information for Claimants</a></li>
	<li><a href="http://labor.ny.gov/ui/how_to_file_claim.shtm">How to File for Benefits</a></li>
	<li><a href="https://applications.labor.ny.gov/IndividualReg/">File a New Claim</a></li>
	<li><a href="https://applications.labor.ny.gov/IndividualReg/">Claim Weekly Benefits</a></li>
	<li><a href="http://labor.ny.gov/ui/claimantinfo/claimant-advocate.shtm">Claimant Advocate</a></li>
	<li><a href="http://labor.ny.gov/ui/claimantinfo/Claimant%20Handbook%20-%20Languages.shtm">Handbooks for Claimants</a></li>
	<li><a href="http://labor.ny.gov/ui/employer.shtm">Information for Employers</a></li>
	<li><a href="http://labor.ny.gov/ui/employerinfo/registering-for-unemployment-insurance.shtm">Employer Registration</a></li>
	<li><a href="http://labor.ny.gov/ui/employerinfo/employer-handbooks.shtm">Handbooks for Employers</a></li>
	<li><a href="http://labor.ny.gov/ui/Authentication/index.shtm">Online Services for Employers</a></li>
	<li><a href="http://labor.ny.gov/stats/uiwages.shtm">Prevailing UI Wages</a></li>
	<li><a href="http://labor.ny.gov/ui/employerinfo/sides-overview.shtm">State Information Data Exchange</a></li>
</ul>