<ul>
	<li><a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minors.shtm">Child Labor</a></li>
	<li><a href="http://labor.ny.gov/workerprotection/laborstandards/secure/child_index.shtm">Child Performer</a></li>
	<li><a href="http://labor.ny.gov/workerprotection/laborstandards/labor_standards.shtm">Employment Laws</a></li>
	<li><a href="http://labor.ny.gov/immigrants/">Immigrants</a></li>
	<li><a href="http://labor.ny.gov/legal/index.shtm">Legal Information</a></li>
	<li><a href="http://www.labor.ny.gov/licenses-permits.shtm">Licenses &amp; Permits </a></li>
	<li><a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minwage.shtm">Minimum Wages</a></li>
	<li><a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Prevailing Wage/Public Work</a></li>
	<li><a href="http://labor.ny.gov/workerprotection/laborstandards/employer/posters.shtm">Required Posters</a></li>
	<li><a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_INDEX.shtm">Safety &amp; Health</a></li>
	<li><a href="http://labor.ny.gov/workforcenypartners/warn/warnportal.shtm">WARN Notice</a></li>
</ul>