<ul>
	<li><a href="http://labor.ny.gov/businessservices/landing.shtm">Business Services</a></li>
	<li><a href="http://labor.ny.gov/businessservices/lookforworkers/lookingforworkersIndex.shtm">Recruitment Services</a></li>
	<li><a href="http://labor.ny.gov/businessservices/services/perm.shtm">Post a Job Opening</a></li>
	<li><a href="https://nytalentbank.labor.ny.gov/talent/login.aspx">Find Talent</a></li>
	<li><a href="http://labor.ny.gov/businessservices/funding.shtm">Funding Opportunities</a></li>
	<li><a href="http://labor.ny.gov/hiring-incentives.shtm">Hiring Incentives</a></li>
	<li><a href="http://labor.ny.gov/stats/index.shtm">Labor Market Information</a></li>
	<li><a href="http://labor.ny.gov/immigrants/agriculture-labor-program/services-for-agriculture-employers.shtm">Services for Agricultural Employers</a></li>
	<li><a href="http://labor.ny.gov/ui/employerinfo/shared-work-program.shtm">Shared Work Program</a></li>
	<li><a href="http://labor.ny.gov/apprenticeship/appsponsor.shtm">Sponsor an Apprenticeship</a></li>
</ul>