
			
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">About Us</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >About Labor</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/about/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/about/history.shtm">Our History</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/about/services.shtm">Our Services</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Contact Us</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/secure/contact">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/how-to-file-a-discrimination-claim.shtm">File Discrimination Complaint</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/secure/foilrequest.shtm">FOIL Request</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/agencyinfo/report-fraud.shtm">Report Fraud</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/warn/warnportal.shtm">WARN Notice</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Divisions</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Divisions</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/dews-index.shtm">Employment & Workforce Solutions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/index.shtm">Equal Opportunity</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Immigrant Policies & Affairs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/index.shtm">Legal</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/information-technology/index.shtm">Planning & Technology</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Research & Statistics</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/unemploymentassistance.shtm">Unemployment Insurance</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/wp_index.shtm">Worker Protection</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Department FAQs</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/faq.shtm">Wages & Hours</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Legal</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PW_faq1.shtm">Prevailing Wage/Public Work</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/faq.shtm">Safety and Health</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/faq.shtm">Unemployment (Claimants)</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/frequently-requested-information.shtm">Unemployment (Employers)</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Newsroom</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/prlaus.shtm">Monthly Press Release - Local Area Unemployment Rates</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">Monthly Press Release - Statewide Jobs Data</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/pressreleases/pressreleases.shtm">Press Releases & Public Notices</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Boards and Councils</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/erb/index.shtm">Employment Relations Board</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/hab/index.htm">Hazard Abatement Board</a>
											</li>
											<li>
												<a href="http://industrialappeals.ny.gov/">Industrial Board of Appeals</a>
											</li>
											<li>
												<a href="http://www.labor.ny.gov/workforcenypartners/lwia.shtm">Local Workforce Investment Boards</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_BOARDS.shtm">Safety and Health</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforce/swib/SWIBAbout.shtm">State Workforce Investment Board</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui-appeal">Unemployment Insurance Appeal Board</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Forms & Publications</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/apprenticeship-forms-and-publications.shtm">Apprenticeship</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/business-services-forms-and-publications.shtm">Business Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/career-services-forms-and-publications.shtm">Career Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/wp/ellsformsandpublications.shtm">Employment Laws/Labor Standards</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/DEOD/deodformsandpublications.shtm">Equal Opportunity</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/formsdocs/dipa/dipa-forms-publications.shtm">Immigrant Policies & Affairs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/wp/pwformsandpublications.shtm">Prevailing Wage/Public Work</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/wp/shformsandpublications.shtm">Safety and Health Documents</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/employer-forms-publications.shtm">Unemployment (Businesses)</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/claimant-forms-and-publications.shtm">Unemployment (Claimants)</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Legal</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Initiatives</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://www.labor.ny.gov/apprenticeship/general/registration.shtm">Apprenticeship</a>
											</li>
																			</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://www.careerzone.ny.gov/">CareerZone</a>
											</li>
											<li>
												<a href="http://www.jobzone.ny.gov/">JobZone</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://ridesafeny.com/">Ride Safe NY</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/shared-work-program.shtm">Shared Work</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/youth">Youth Portal</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Workforce Professionals</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/career-center-events.shtm">NYS Career Center Events</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/career-center-locator">New York State Career Centers</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/tools.shtm">Programs and Tools</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/training-events.shtm">Training and Events</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
