 <div class="nys-global-footer">
      <div class="footer-container">
        <h3>Department of Labor</h3>
        <div class="align-left margin-left margin-bottom padding-left padding-bottom">
          <img src="//labor.ny.gov/css/apps/v.0.5.0/images/dol-footer-ajc-tagline.png" alt="A proud partner of the American Job Center network">
        </div>
        <div class="footer-col">
          <h4>About Us</h4>
          <ul>
            <li><a href="/about/">Our Mission</a></li>
            <li><a href="/about/services.shtm">Our Services</a></li>
            <li><a href="/about/history.shtm">Our History</a></li>
            <li><a href="/dol-newsroom.shtm">Newsroom</a></li>
            <li><a href="/agencyinfo/commissioner.shtm">Commissioner</a></li>
            <li><a href="/agencyinfo/contracts/contract-bid-grant-opportunities.shtm">Contract, Bid &amp; Grant Opportunities</a></li>
            <li><a href="/dol-contact.shtm">Contact Us</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Boards</h4>
          <ul>
            <li><a href="/hab/">Hazard Abatement Board</a></li>
            <li><a href="http://industrialappeals.ny.gov">Industrial Board of Appeals</a></li>
            <li><a href="/workforcenypartners/lwda.shtm">Local Workforce Development Boards</a></li>
            <li><a href="https://perb.ny.gov">Public Employment Relations Board</a></li>
            <li><a href="/workforce/swib/SWIBAbout.shtm">State Workforce Investment Board</a></li>
            <li><a href="http://uiappeals.ny.gov">Unemployment Insurance Appeal Board</a></li>
           </ul>
        </div>
        <div class="footer-col">
          <h4>Initiatives</h4>
          <ul>
            <li><a href="/apprenticeship/appindex.shtm">Apprenticeship</a></li>
            <li><a href="http://www.careerzone.ny.gov">CareerZone</a></li>
            <li><a href="https://www.ny.gov/programs/new-york-state-paid-family-leave">Paid Family Leave</a></li>
            <li><a href="http://www.jobzone.ny.gov">JobZone</a></li>
            <li><a href="http://nyworks.ny.gov/">Regional Economic Development Councils</a></li>
            <li><a href="/ridesafeny/">Ride Safe NY</a></li>
            <li><a href="/ui/employerinfo/shared-work-program.shtm">Shared Work</a></li>
            <li><a href="/youth">Youth Portal</a></li>
          </ul> 
        </div>
        <div class="footer-col">
          <h4>Resources</h4>
          <ul>
            <li><a href="/agencyinfo/accessibility.shtm">Accessibility Policy</a></li>
            <li><a href="https://www.labor.ny.gov/secure/foilrequest.shtm">Freedom of Information Law (FOIL)</a></li>
            <li><a href="/privacy.shtm">Privacy Policy</a></li>
            <li><a href="/agencyinfo/report-fraud.shtm">Report Fraud</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Language Assistance</h4>
          <ul>
            <li><a href="/immigrants/language-access-complaint.shtm#spanish">Español</a></li>
            <li><a href="/immigrants/language-access-complaint.shtm#chinese">中文</a></li>
            <li><a href="/immigrants/language-access-complaint.shtm#russian">Русскийy</a></li>
            <li><a href="/immigrants/language-access-complaint.shtm#italian">Italiano</a></li>
            <li><a href="/immigrants/language-access-complaint.shtm#haitian-creole">Kreyòl ayisyen</a></li>
            <li><a href="/immigrants/language-access-complaint.shtm#korean">한국어</a></li>
            <li><a href="/immigrants/language-access-complaint.shtm#polish">Polski</a></li>
            <li><a href="/immigrants/language-access.shtm">More Information</a></li>
          </ul>
        </div>
       <div class="social-media">
          <div class="social-media-title">
            <h4>CONNECT WITH US</h4>
          </div>
          <div class="social-media-links">
            <ul>
              <li>
                <a href="http://www.facebook.com/nyslabor" target="_blank" class="ux-no-link-icon">
                  <span class="icon-social-facebook"></span>
                  <span>FACEBOOK</span>
                </a>
              </li>
              <li>
                <a href="http://twitter.com/nyslabor" target="_blank" class="ux-no-link-icon">
                  <span class="icon-social-twitter"></span>
                  <span>TWITTER</span>
                </a>
              </li>
              <li>
                <a href="http://www.youtube.com/user/NYSLabor" target="_blank" class="ux-no-link-icon">
                  <span class="icon-social-youtube"></span>
                  <span>YOUTUBE</span>
                </a>
              </li>
              <li>
                <a href="http://instagram.com/nyslabor" target="_blank" class="ux-no-link-icon">
                  <span class="icon-social-instagram"></span>
                  <span>INSTAGRAM</span>
                </a>
              </li>
              <li>
                <a href="https://www.linkedin.com/company/new-york-state-department-of-labor" target="_blank" class="ux-no-link-icon">
                  <span class="icon-social-linkedin"></span>
                  <span>LINKED IN</span>
                </a>
              </li>
            </ul>
          </div>
          <div class="social-media">
          <div class="social-media-title" style="padding-top: 25px;">
            <h4>REGISTER TO VOTE</h4>
          </div>
          <div class="social-media-links">
            <ul>
              <li><strong style="font-family: arial, sans-serif;">Sign up online or download and mail in your application</strong> <a href="//www.ny.gov/services/register-vote" style="background-color:#09464c; color:white; min-width: 270px; padding:16px 0px; text-decoration: none; letter-spacing: 1px; vertical-align: middle; border: 1px solid #fff; font-size: 13px; text-transform: uppercase; display:inline-block;" target="_blank" class="ux-no-link-icon ext_track" onclick="_gaq.push(['_trackEvent', 'external_links', '//www.ny.gov/services/register-vote', '//www.ny.gov/services/register-vote']);_gaq.push(['_trackEvent', 'gov/services/register-vote', 'www', 'www']);"> Register to Vote</a> </li>
              
            </ul>
          </div>
    </div>
        </div>
      </div>
      <!-- end .footer-container -->
    </div>
    <!-- end .nys-global-footer -->
