<ul>
	<li><a href="https://labor.ny.gov/careerservices/CareerServicesIndex.shtm">Tips for Job Seekers</a></li>
	<li><a href="https://labor.ny.gov/apprenticeship/appindex.shtm">Apprenticeship</a></li>
	<li><a href="https://labor.ny.gov/workforcenypartners/career-center-events.shtm">Career Center Events &amp; Recruitments </a></li>
	<li><a href="https://labor.ny.gov/career-center-locator/">Career Center Locator</a></li>
	<li><a href="https://labor.ny.gov/careerservices/jobzone/index.shtm">Career Exploration for Adults (JobZone)</a></li>
	<li><a href="https://www.careerzone.ny.gov/views/careerzone/index.jsf">Career Exploration for Youth (CareerZone)</a></li>
	<li><a href="https://www.labor.ny.gov/stats/lsproj.shtm">Employment Projections</a></li>
	<li><a href="https://labor.ny.gov/jobs/regional.shtm">Jobs Express - Openings in NYS</a></li>
	<li><a href="https://labor.ny.gov/stats/cslist.shtm">List of Civil Service Websites</a></li>
	<li><a href="https://newyork.usnlx.com/">State Job Bank</a></li>
	<li><a href="https://labor.ny.gov/stats/lstrain.shtm">Occupational Licenses &amp; Certifications </a></li>
	<li><a href="https://labor.ny.gov/stats/lswage2.asp">Occupational Wages</a></li>
	<li><a href="https://labor.ny.gov/youth/">Youth Portal</a></li>
</ul>