fragment VideoEmbed on ParagraphVideoEmbed {
  description: fieldDescription {
    content: processed
  }
  headline: fieldHeadline
  partOfNavigator: fieldPartOfNavigatorSidebar
  title: fieldTitle
  videoLink: fieldVeVideoLink
  videoTitle: fieldVeVideoTitle
  coverImage: fieldVeCoverImage {
    entity {
      entityLabel... on MediaImage {
        imageDescription: fieldMiDescription {
          content: processed
        }
        img: fieldMediaImage {
          derivative(style: COVERIMAGE660X400) {
            url
          }
        }
      }
    }
  }
}
